on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.8', '9.4.5', '9.6.2']
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    name: Build with GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v2.4.3
        with:
          cabal-version: latest
          ghc-version: ${{ matrix.ghc }}
      - run: cabal v2-test
